services:
  backend:
    profiles:
      - prod
    image: ${DOCKER_USER}/docker-project-backend:${IMAGE_TAG:-latest}
    build: !reset null
    pull_policy: always

  frontend:
    profiles:
      - prod
    image: ${DOCKER_USER}/docker-project-frontend:${IMAGE_TAG:-latest}
    build: !reset null
    pull_policy: always
