server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /momo-store/ {
        rewrite ^/momo-store/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location = /momo-store {
        return 301 /momo-store/;
    }

    location = / {
        return 302 /momo-store/;
    }
}
